### ISSUE TITLE
Support for Apple Magic Mouse Panning

### ISSUE THREAD

**Issue by letsgamedev** [nklbdev/godot-enchanced-tile-map-editor#28]
I looked into the _input events and when I use panning gestures with the apple magic mouse the event InputEventPanGesture is triggered. The only member of that is a delta. This could be used for panning in the map review.

https://docs.godotengine.org/de/stable/classes/class_inputeventpangesture.html

**Comment by nklbdev** [comment]
Thank you, Tom, great idea! I will implement it soon.

**Comment by nklbdev** [comment]
@letsgamedev, please, try current version out and give me feedback. I haven't Apple devices((. Unfortunately, on the trackpad of a laptop with Windows, I was unable to make a panoramic gesture.

I also reduced the zoom speed a little. I hope it will be more comfortable now.

**Comment by letsgamedev** [comment]
Hi, i made a pull request for this isssue. Just had to make little changes to your code.

**Comment by nklbdev** [comment]
@letsgamedev, thank you! It is the first pull request for me on GitHub!
