### ISSUE TITLE
Pick up where I left

### ISSUE THREAD

**Issue by letsgamedev** [nklbdev/godot-enchanced-tile-map-editor#35]
Hi there!
Occasionally we hack around with you plugin but there is a thing we could not figure out.

If we have two tilemaps and swap between them, the UI of you editor resets itself every time.
So our Desinger has to click on the tileset and on the tile in your Editor again after selecting the TileMap nodes in the editor.

Do you have an Idea how we could achive that the editor remembers the last selected tileset and tile for the different TileMap Nodes and opens them automatically?

**Comment by nklbdev** [comment]
Hello, Tom! Yes, I can do it in a week or less
